on:
  push:
    tags:
      - "*"

name: Release Bukkt to JitPack

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            #### Release ${{ github.ref }}

            Dependency:

            ```kotlin
            repositories {
                maven { setUrl("https://jitpack.io/") }
            }

            dependencies {
                implementation("com.github.rqbik", "bukkt", "${{ github.event.release.tag_name }}")
            }
            ```
          draft: false
          prerelease: false